### ISSUE TITLE
初始化專案配置

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/goodjob-admin-page#1]
目前需要配置有幾種技術：

- [ ] graphql (apollo?)
- [x] react
- [x] ant design https://github.com/ant-design/ant-design/

**Comment by WendellLiu** [comment]
@peteranny 
我會在這裏回一下我看到的一些疑慮。

1. 蠻多版本似乎都太舊了，除了webpack、eslint、babel 外，react、react-dom 本身也有點舊。倒不是什麼迷思，例如weback, babel, react 你用的版本到目前的有蠻大的差異，寫下去未來要升級有點麻煩。
2. 看npm script ，release 那邊好像是其他專案使用的？
3. 看起來還沒有css 相關的設置？
4. 可以參考create react app或 https://github.com/WendellLiu/large-react-app-kit （我這也是create react app 改過來的），原本是想直接用我這個，主要是因為這次是用graphql ，所以資料流上應該會有差異，就沒用了，但你還是可以參考一下。

**Comment by peteranny** [comment]
好的，那我改用你的

**Comment by mark86092** [comment]
除了升級外，我猜最大的麻煩是要查文件不好找，所以還是用 @WendellLiu  建議的來做

BTW, LaborUnion 就是從 create-react-app 套的，上面要加上 react-router 還蠻容易

**Comment by WendellLiu** [comment]
@peteranny 
假如你最後選擇用我的kit ，注意一下：
1. redux 是不是需要可以再想想
https://medium.com/@matt.krick/replacing-redux-with-relay-47ed085bfafe
graphql 可能可以研究一下relay ，但這我也沒碰過，只是之前在看graphql 看到
2. flow type 你可以就忽略，看你決定。

**Comment by mark86092** [comment]
個人猜想：配合 react context api，不用到 redux 應該可行，graphql 基本款也行

可以不用一次導入太多，不過如 @WendellLiu 說的可以想想。如果有要 push 新的技能，這個 repo 是沒壓力的可以亂改造

**Comment by WendellLiu** [comment]
update:
還需要配置graphql ，因此拉回in progress
另外目前預計會使用apollo client ，也搭配使用他們自己的local state management ，因此也會移除redux 相關。
