### ISSUE TITLE
網頁 cookie 問題

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/goodjob-admin-page#36]
造訪 https://admin-page-stage.goodjob.life/time-and-salary 得到錯誤，沒辦法顯示資料

![image](https://user-images.githubusercontent.com/1908007/46242859-1f5c8000-c400-11e8-8f71-3d9934858522.png)

**Comment by WendellLiu** [comment]
應該是因為 `credentials: 'include'` ，但我以為這是預期（因為後端還沒上）的結果？

**Comment by WendellLiu** [comment]
看起來好像不是預期，不過的確comment 那段就可了。

**Comment by WendellLiu** [comment]
@mark86092 
看起來沒錯，express cors option 加上 `credentials: true` 就能上，這樣應該是可預期的？

**Comment by mark86092** [comment]
@WendellLiu 看來按照紅字的解是OK的

妙的是在 local 端的 cors 似乎沒問題（你今天 demo 是有成功 request）

**Comment by WendellLiu** [comment]
喔喔，因為我comment 掉才demo 。因為我以為是預期的。
