### ISSUE TITLE
經驗表格（View）

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/goodjob-admin-page#4]
- [x] 請留最左欄的checkbox 以利接下來的操作issue 選取
- [x] 能夠點選header 排序
- [x] fixed header
- [x] 能以id 來搜尋
- [x] 表格欄位： **id**, **公司**, **職稱**, **標題**, **地區**, **封存狀態**,  **封存理由**

**Comment by barry800414** [comment]
`公司`、`職稱`、`內文` 都要有，經驗分享很多沒有意義的一行文。

**Comment by WendellLiu** [comment]
@barry800414 
這裡已經更新了
不過「內文」頗多欄位，要放在表格欄位上不太妥，未來若要對這部分審查，再另設計UI 來使用比較適合。

**Comment by peteranny** [comment]
> 最左欄的checkbox 以利接下來的操作issue 選取
想問這句什麼意思?

**Comment by WendellLiu** [comment]
cc: @peteranny 
這裡還需要接上API 資料，因此先不close，也拉回to do。
