### ISSUE TITLE
列表表格顯示已封存

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/goodjob-admin-page#40]
目前的列表上看不到是否已經封存，要點進 Edit 才能看，有點麻煩

**Comment by WendellLiu** [comment]
![2018-10-13 12 40 33](https://user-images.githubusercontent.com/8898129/46901386-5002e600-cee5-11e8-9a5d-d78a36a9fd90.png)

你是指這個嗎?

**Comment by mark86092** [comment]
誒誒！這是在哪裡實作，我沒看到

**Comment by mark86092** [comment]
我發現了，我螢幕不夠寬，所以遮住了

**Comment by mark86092** [comment]
不過或許可以考慮調整欄位位置與寬度，讓資訊比較容易一覽
