### ISSUE TITLE
薪資工時表格（View）

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/goodjob-admin-page#5]
- [x] 請留最左欄的checkbox 以利接下來的操作issue 選取
- [x] 能夠點選header 排序
- [x] fixed header
- [x] 能以id 來搜尋
- [x] 表格欄位： **id**, **公司**, **職稱**, **薪資種類**, **薪資數量**, **實際平均工時**, **一週總工時**, **封存狀態**, **封存理由**

**Comment by barry800414** [comment]
`公司`、`職稱`、`薪資種類`、`薪資數量`、`工時` 相關欄位、`估計時薪` 都要有

**Comment by WendellLiu** [comment]
@barry800414 
這裡已經更新了

**Comment by WendellLiu** [comment]
cc: @peteranny 
這裡還需要接上API 資料，因此先不close，也拉回to do。
