### ISSUE TITLE
面試經驗的地方展開，內容都是會是同一篇

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/goodjob-admin-page#60]
<img width="554" alt="螢幕快照 2019-07-17 下午10 10 23" src="https://user-images.githubusercontent.com/3805975/61382702-d8cd0900-a8df-11e9-98e5-76851d37fefd.png">
<img width="548" alt="螢幕快照 2019-07-17 下午10 10 31" src="https://user-images.githubusercontent.com/3805975/61382703-d8cd0900-a8df-11e9-88a8-82adf0d05be1.png">

點開 `5d2f1aea649c890012553e9a` & `5d2f12b2649c890012553beb` 這兩個面試經驗，下方的內容會是同一個

`5d2f12b2649c890012553beb ` 是錯誤的

**Comment by barry800414** [comment]
再補一張圖：
<img width="949" alt="螢幕快照 2020-01-05 上午10 13 19" src="https://user-images.githubusercontent.com/3805975/71774126-08fa8800-2fa4-11ea-9317-5ad1f5a5bd4f.png">

**Comment by barry800414** [comment]
目前有以下發現：
- https://github.com/goodjoblife/goodjob-admin-page/blob/master/src/components/Admin/Interview.js#L128 這行的 interview_experiences 裡面的 sections 就錯了
- 但用 network dev tool 看 graphql api 的 response 並沒有錯

也就是說，滿可能是 graphql 套件的問題

**Comment by WendellLiu** [comment]
`5d2f1aea649c890012553e9a`
<img width="1436" alt="截圖 2020-01-06 下午8 36 05" src="https://user-images.githubusercontent.com/8898129/71818526-38081b00-30c4-11ea-8cef-6db4c7a581e8.png">

`5d2f12b2649c890012553beb`
<img width="1422" alt="截圖 2020-01-06 下午8 36 13" src="https://user-images.githubusercontent.com/8898129/71818527-38a0b180-30c4-11ea-8bfa-2a447dbf8031.png">

我這邊開是看到不同資料，還是你是指別地方？

**Comment by WendellLiu** [comment]
不過關於你回覆裡的情形，倒是可以在local(connect to staging be server) 重現
我就以這個修囉
